# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.sort_sort_field import SortSortField

class TestSortSortField(unittest.TestCase):
    """SortSortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortSortField(self):
        """Test SortSortField"""
        # inst = SortSortField()

if __name__ == '__main__':
    unittest.main()
