# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_bulk_update_response import CustomerBulkUpdateResponse

class TestCustomerBulkUpdateResponse(unittest.TestCase):
    """CustomerBulkUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerBulkUpdateResponse:
        """Test CustomerBulkUpdateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerBulkUpdateResponse`
        """
        model = CustomerBulkUpdateResponse()
        if include_optional:
            return CustomerBulkUpdateResponse(
                customer_ids = [
                    ''
                    ]
            )
        else:
            return CustomerBulkUpdateResponse(
        )
        """

    def testCustomerBulkUpdateResponse(self):
        """Test CustomerBulkUpdateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
