# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_address_update_request import CustomerAddressUpdateRequest

class TestCustomerAddressUpdateRequest(unittest.TestCase):
    """CustomerAddressUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerAddressUpdateRequest:
        """Test CustomerAddressUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerAddressUpdateRequest`
        """
        model = CustomerAddressUpdateRequest()
        if include_optional:
            return CustomerAddressUpdateRequest(
                tenant_id = '',
                customer_id = '',
                id = '',
                address = customer.models.customer_address_entity.customerAddressEntity(
                    em = customer.models.customer_em_fields.customerEMFields(
                        tenant_id = '', 
                        entity_type = '', 
                        entity_code = '', ), 
                    name = '', 
                    surname = '', 
                    street = '', 
                    number = '', 
                    zip = '', 
                    city = '', 
                    province = '', 
                    phone_number = '', 
                    fiscal_code = '', 
                    vat_number = '', 
                    kind = 'SHIPPING', 
                    default = True, 
                    country = '', 
                    attributes = {
                        'key' : {
                            'key' : None
                            }
                        }, ),
                field_mask = ''
            )
        else:
            return CustomerAddressUpdateRequest(
        )
        """

    def testCustomerAddressUpdateRequest(self):
        """Test CustomerAddressUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
