# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_consent_source import CustomerConsentSource

class TestCustomerConsentSource(unittest.TestCase):
    """CustomerConsentSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerConsentSource(self):
        """Test CustomerConsentSource"""
        # inst = CustomerConsentSource()

if __name__ == '__main__':
    unittest.main()
