# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_address_create_request_kind import CustomerAddressCreateRequestKind

class TestCustomerAddressCreateRequestKind(unittest.TestCase):
    """CustomerAddressCreateRequestKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerAddressCreateRequestKind(self):
        """Test CustomerAddressCreateRequestKind"""
        # inst = CustomerAddressCreateRequestKind()

if __name__ == '__main__':
    unittest.main()
