# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.sort_sort_order import SortSortOrder

class TestSortSortOrder(unittest.TestCase):
    """SortSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortSortOrder(self):
        """Test SortSortOrder"""
        # inst = SortSortOrder()

if __name__ == '__main__':
    unittest.main()
