# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_address_customer_response import CustomerAddressCustomerResponse

class TestCustomerAddressCustomerResponse(unittest.TestCase):
    """CustomerAddressCustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerAddressCustomerResponse:
        """Test CustomerAddressCustomerResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerAddressCustomerResponse`
        """
        model = CustomerAddressCustomerResponse()
        if include_optional:
            return CustomerAddressCustomerResponse(
                em = customer.models.customer_em_fields.customerEMFields(
                    tenant_id = '', 
                    entity_type = '', 
                    entity_code = '', ),
                grn = '',
                id = '',
                name = '',
                surname = '',
                street = '',
                number = '',
                zip = '',
                city = '',
                province = '',
                phone_number = '',
                fiscal_code = '',
                vat_number = '',
                kind = 'SHIPPING',
                default = True,
                country = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    }
            )
        else:
            return CustomerAddressCustomerResponse(
        )
        """

    def testCustomerAddressCustomerResponse(self):
        """Test CustomerAddressCustomerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
