# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from customer.api.customer_api import CustomerApi


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerApi()

    def tearDown(self) -> None:
        pass

    def test_customer_acquire_subscriber(self) -> None:
        """Test case for customer_acquire_subscriber

        """
        pass

    def test_customer_acquire_subscriber2(self) -> None:
        """Test case for customer_acquire_subscriber2

        """
        pass

    def test_customer_acquire_unsubscriber(self) -> None:
        """Test case for customer_acquire_unsubscriber

        """
        pass

    def test_customer_acquire_unsubscriber2(self) -> None:
        """Test case for customer_acquire_unsubscriber2

        """
        pass

    def test_customer_add_customer_to_group(self) -> None:
        """Test case for customer_add_customer_to_group

        """
        pass

    def test_customer_add_customer_to_group2(self) -> None:
        """Test case for customer_add_customer_to_group2

        """
        pass

    def test_customer_assign_agent(self) -> None:
        """Test case for customer_assign_agent

        """
        pass

    def test_customer_bulk_update(self) -> None:
        """Test case for customer_bulk_update

        """
        pass

    def test_customer_bulk_update2(self) -> None:
        """Test case for customer_bulk_update2

        """
        pass

    def test_customer_create(self) -> None:
        """Test case for customer_create

        """
        pass

    def test_customer_create2(self) -> None:
        """Test case for customer_create2

        """
        pass

    def test_customer_create_address(self) -> None:
        """Test case for customer_create_address

        """
        pass

    def test_customer_create_address2(self) -> None:
        """Test case for customer_create_address2

        """
        pass

    def test_customer_create_group(self) -> None:
        """Test case for customer_create_group

        """
        pass

    def test_customer_create_group2(self) -> None:
        """Test case for customer_create_group2

        """
        pass

    def test_customer_create_subscriber(self) -> None:
        """Test case for customer_create_subscriber

        """
        pass

    def test_customer_create_subscriber2(self) -> None:
        """Test case for customer_create_subscriber2

        """
        pass

    def test_customer_delete_address(self) -> None:
        """Test case for customer_delete_address

        """
        pass

    def test_customer_delete_address2(self) -> None:
        """Test case for customer_delete_address2

        """
        pass

    def test_customer_delete_group(self) -> None:
        """Test case for customer_delete_group

        """
        pass

    def test_customer_delete_group2(self) -> None:
        """Test case for customer_delete_group2

        """
        pass

    def test_customer_find(self) -> None:
        """Test case for customer_find

        """
        pass

    def test_customer_find2(self) -> None:
        """Test case for customer_find2

        """
        pass

    def test_customer_find_by_email(self) -> None:
        """Test case for customer_find_by_email

        """
        pass

    def test_customer_find_by_email2(self) -> None:
        """Test case for customer_find_by_email2

        """
        pass

    def test_customer_find_by_id(self) -> None:
        """Test case for customer_find_by_id

        """
        pass

    def test_customer_find_by_id2(self) -> None:
        """Test case for customer_find_by_id2

        """
        pass

    def test_customer_find_subscriber_by_email(self) -> None:
        """Test case for customer_find_subscriber_by_email

        """
        pass

    def test_customer_find_subscriber_by_email2(self) -> None:
        """Test case for customer_find_subscriber_by_email2

        """
        pass

    def test_customer_find_subscriber_by_id(self) -> None:
        """Test case for customer_find_subscriber_by_id

        """
        pass

    def test_customer_find_subscriber_by_id2(self) -> None:
        """Test case for customer_find_subscriber_by_id2

        """
        pass

    def test_customer_get_group_by_code(self) -> None:
        """Test case for customer_get_group_by_code

        """
        pass

    def test_customer_get_group_by_code2(self) -> None:
        """Test case for customer_get_group_by_code2

        """
        pass

    def test_customer_get_group_by_id(self) -> None:
        """Test case for customer_get_group_by_id

        """
        pass

    def test_customer_get_group_by_id2(self) -> None:
        """Test case for customer_get_group_by_id2

        """
        pass

    def test_customer_grant_permissions(self) -> None:
        """Test case for customer_grant_permissions

        """
        pass

    def test_customer_grant_permissions2(self) -> None:
        """Test case for customer_grant_permissions2

        """
        pass

    def test_customer_list_consents(self) -> None:
        """Test case for customer_list_consents

        ListConsents list all consents of a customer
        """
        pass

    def test_customer_list_customers(self) -> None:
        """Test case for customer_list_customers

        """
        pass

    def test_customer_list_customers2(self) -> None:
        """Test case for customer_list_customers2

        """
        pass

    def test_customer_list_groups(self) -> None:
        """Test case for customer_list_groups

        """
        pass

    def test_customer_list_groups2(self) -> None:
        """Test case for customer_list_groups2

        """
        pass

    def test_customer_remove_customer_from_group(self) -> None:
        """Test case for customer_remove_customer_from_group

        """
        pass

    def test_customer_remove_customer_from_group2(self) -> None:
        """Test case for customer_remove_customer_from_group2

        """
        pass

    def test_customer_remove_default_address(self) -> None:
        """Test case for customer_remove_default_address

        """
        pass

    def test_customer_remove_default_address2(self) -> None:
        """Test case for customer_remove_default_address2

        """
        pass

    def test_customer_revoke_permissions(self) -> None:
        """Test case for customer_revoke_permissions

        """
        pass

    def test_customer_revoke_permissions2(self) -> None:
        """Test case for customer_revoke_permissions2

        """
        pass

    def test_customer_search(self) -> None:
        """Test case for customer_search

        """
        pass

    def test_customer_search2(self) -> None:
        """Test case for customer_search2

        """
        pass

    def test_customer_set_default_address(self) -> None:
        """Test case for customer_set_default_address

        """
        pass

    def test_customer_set_default_address2(self) -> None:
        """Test case for customer_set_default_address2

        """
        pass

    def test_customer_set_permissions(self) -> None:
        """Test case for customer_set_permissions

        """
        pass

    def test_customer_set_permissions2(self) -> None:
        """Test case for customer_set_permissions2

        """
        pass

    def test_customer_unassign_agent(self) -> None:
        """Test case for customer_unassign_agent

        """
        pass

    def test_customer_unsubscribe(self) -> None:
        """Test case for customer_unsubscribe

        """
        pass

    def test_customer_unsubscribe2(self) -> None:
        """Test case for customer_unsubscribe2

        """
        pass

    def test_customer_update(self) -> None:
        """Test case for customer_update

        """
        pass

    def test_customer_update2(self) -> None:
        """Test case for customer_update2

        """
        pass

    def test_customer_update_address(self) -> None:
        """Test case for customer_update_address

        """
        pass

    def test_customer_update_address2(self) -> None:
        """Test case for customer_update_address2

        """
        pass

    def test_customer_update_group(self) -> None:
        """Test case for customer_update_group

        """
        pass

    def test_customer_update_group2(self) -> None:
        """Test case for customer_update_group2

        """
        pass

    def test_customer_update_subscriber(self) -> None:
        """Test case for customer_update_subscriber

        """
        pass

    def test_customer_update_subscriber2(self) -> None:
        """Test case for customer_update_subscriber2

        """
        pass


if __name__ == '__main__':
    unittest.main()
