# coding: utf-8

"""
    CDP Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from customer.models.customer_list_consents_request import CustomerListConsentsRequest

class TestCustomerListConsentsRequest(unittest.TestCase):
    """CustomerListConsentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerListConsentsRequest:
        """Test CustomerListConsentsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerListConsentsRequest`
        """
        model = CustomerListConsentsRequest()
        if include_optional:
            return CustomerListConsentsRequest(
                tenant_id = '',
                page_size = 56,
                page_token = '',
                sorts = [
                    customer.models.list_consents_request_sort.ListConsentsRequestSort(
                        field = 'UNKNOWN', 
                        order = 'DESC', )
                    ],
                filters_mask = '',
                filters = customer.models.list_consents_request_filters.ListConsentsRequestFilters(
                    subject_ids = [
                        ''
                        ], )
            )
        else:
            return CustomerListConsentsRequest(
        )
        """

    def testCustomerListConsentsRequest(self):
        """Test CustomerListConsentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
